version: '3'

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '6000:3000'
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=production
